trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: JavaToolInstaller@0
      displayName: 'Install Java 17'
      inputs:
        versionSpec: '17'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
    - task: Maven@3
      displayName: 'Build Java project with Maven'
      inputs:
        mavenPomFile: '$(Build.SourcesDirectory)/lab052/pom.xml'
        goals: 'package'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomFile: '$(Build.SourcesDirectory)/lab052/pom.xml'
    - script: |
        ls -R $(Build.SourcesDirectory)/lab052
      displayName: 'List directory contents for debugging'
    - task: Docker@2
      displayName: 'Build Docker image'
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/lab052/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)/lab052'
        arguments: '--no-cache' # Optional: disable caching to avoid cache issues
        tags: |
          $(tag)