apiVersion: apps/v1
kind: Deployment
metadata:
  name: hworld
  namespace: integrations
  labels:
    app: hworld
spec:
  replicas: 1
  progressDeadlineSeconds: 600  # From your original
  revisionHistoryLimit: 10      # From your original
  selector:
    matchLabels:
      app: hworld
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hworld
    spec:
      containers:
      - name: hworld
        image: sridharavshastry/hworld:290
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000   # Required for Service targetPort
        resources:
          limits:               # Added for production
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
        livenessProbe:         # Added for health checks
          httpGet:
            path: /health       # Replace with your app's health endpoint
            port: 9000
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:        # Added for traffic routing
          httpGet:
            path: /ready       # Replace with your app's ready endpoint
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 10
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: hworld
  namespace: integrations
  labels:
    app: hworld
spec:
  type: NodePort
  selector:
    app: hworld
  ports:
  - port: 9000
    targetPort: 9000
    nodePort: 30339   # Keep if you need this specific port
