apiVersion: apps/v1
kind: Deployment
metadata:
  name: hworld
  namespace: integrations
  labels:
    app: hworld
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hworld
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hworld
    spec:
      containers:
      - name: hworld
        image: sridharavshastry/hworld:290
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: hworld
  namespace: integrations
  labels:
    app: hworld
spec:
  type: NodePort
  selector:
    app: hworld
  ports:
  - port: 9000
    targetPort: 9000
    nodePort: 30339
